### ISSUE TITLE
vs2013编译失败

### ISSUE THREAD

**Issue by linjx** [ketoo/NoahGameFrame#1]
1>  logging.cc
1>F:\NoahGameFrame\Dependencies\glog-0.3.3\src\windows\port.h(117): warning C4005: “va_copy”: 宏重定义
1>          D:\Microsoft Visual Studio 12.0\VC\include\stdarg.h(37) : 参见“va_copy”的前一个定义
1>..\..\src\logging.cc(75): error C2039: “min”: 不是“std”的成员
1>..\..\src\logging.cc(75): error C2873: “min”: 符号不能用在 using 声明中
1>..\..\src\logging.cc(586): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>..\..\src\logging.cc(719): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
1>..\..\src\logging.cc(744): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>..\..\src\logging.cc(754): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>..\..\src\logging.cc(1033): warning C4267: “初始化”: 从“size_t”转换到“const int”，可能丢失数据
1>..\..\src\logging.cc(1314): warning C4267: “初始化”: 从“size_t”转换到“const int”，可能丢失数据
1>..\..\src\logging.cc(1386): error C2065: “min”: 未声明的标识符
1>..\..\src\logging.cc(1386): error C2062: 意外的类型“int”
1>..\..\src\logging.cc(1409): warning C4267: “参数”: 从“size_t”转换到“unsigned int”，可能丢失数据
1>..\..\src\logging.cc(1487): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>..\..\src\logging.cc(1500): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
========== 生成:  成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

PS:
例如编译NFDep libglog_static, 有以上的报错

**Comment by eliteYang** [comment]
你好，因我这边没有2013环境，请问vs2013编译报什么错，方便的话截个图看看，谢谢！

**Comment by eliteYang** [comment]
@linjx 在预编译宏里加上NOMINMAX，现在我们已经不用glog了，因为有些冗余，已经改用easylogging++了，你可以更新下，谢谢
