### ISSUE TITLE
Database is missing. [request]

### ISSUE THREAD

**Issue by Adizbek** [ketoo/NoahGameFrame#107]
There is no sql except `app_test.sql`.

Where is data to run Unity ? After login OnWorldList packet received but nothing in it. Is there any example ?

**Comment by Adizbek** [comment]
After searching. I have found generated Struct/Nframe.sql

Is there any instructions to setup database ? I have no idea how to start?

**Comment by ketoo** [comment]
I think this problem is related with the problem https://github.com/ketoo/NoahGameFrame/issues/105

Now NF using Redis as the database.

I know from your graph[22:56:49] that your account sign-in was succeeded. The reason you can't get the world list that is your world server was crashed, could you please show me more log which comes from the world server?

Normally we run the shell script runxd.sh(with Database) or rund.sh (without Database), you can see the shell file to know how to run a world server.

**Comment by Adizbek** [comment]
There is no file named runxd.sh in my folder.

**Comment by ketoo** [comment]
So you run the shell script named rund.sh?

I will test it late.

**Comment by Adizbek** [comment]
@ketoo should I install redis before?

**Comment by ketoo** [comment]
You can the script rund.sh without Database, wait a moment lease, i am testing for this issue.

**Comment by ketoo** [comment]
Got it.

bool NFCWorldToMasterModule::Init()
{
	m_pNetClientModule = pPluginManager->FindModule<NFINetClientModule>();
	m_pNetModule = pPluginManager->FindModule<NFINetModule>();
	m_pClassModule = pPluginManager->FindModule<NFIClassModule>();
	m_pElementModule = pPluginManager->FindModule<NFIElementModule>();
	m_pLogModule = pPluginManager->FindModule<NFILogModule>();
	m_pWorldNet_ServerModule = pPluginManager->FindModule<NFIWorldNet_ServerModule>();
	m_pSecurityModule = pPluginManager->FindModule<NFISecurityModule>();

	return true;
}

Assert:
m_pSecurityModule = pPluginManager->FindModule<NFISecurityModule>();

How to fix:
const std::string NFSecurityPlugin::GetPluginName()
{
	return GET_CLASS_NAME(NFCSecurityPlugin);
}
======>>>>
const std::string NFSecurityPlugin::GetPluginName()
{
	return GET_CLASS_NAME(NFSecurityPlugin);
}

Now fixed.
https://github.com/ketoo/NoahGameFrame/commit/32bcbda2f06d563400966c1590d90214ed9457cd

**Comment by Adizbek** [comment]
Yes. Fixed.
<img width="1280" alt="2018-07-15 17 22 38" src="https://user-images.githubusercontent.com/10253982/42734019-fae30324-8855-11e8-98e4-1818f1a1d031.png">

But the most interesting thing. I have logged in with the same login on the same time and playing.

**Comment by ketoo** [comment]
Yes, the old one you logged should be kicked, I will fix it soon.
