### ISSUE TITLE
Freeze while running runtutoriald.sh

### ISSUE THREAD

**Issue by TenMei** [ketoo/NoahGameFrame#109]
Out put:

<img width="717" alt="screen shot 2018-07-28 at 07 46 06" src="https://user-images.githubusercontent.com/4993410/43351309-69f4c98a-923a-11e8-812e-3121e896a7ec.png">

**Comment by TenMei** [comment]
I wonder why Unity (client) needs file (LogicClass.NF) from server side.

**Comment by TenMei** [comment]
Sorry, but how can I check the error log in this case?

**Comment by ketoo** [comment]
The log folder is _Out/Debug/log when you running under debug mode.
