### ISSUE TITLE
Where is MySQLPlugin in 5.3.0？

### ISSUE THREAD

**Issue by JiangWang01** [ketoo/NoahGameFrame#120]
5.2.4的MySQLPlugin在5.3.0及之后版本为什么去掉了？

**Comment by ketoo** [comment]
通常情况下，我认为有nosql已经足够使用了。
如果部分开发者或者运维人员觉得不够使用，可以在dbserver接入一层，只用redis当cache。

不使用mysql并不影响项目开发和程序调试，等上线之前，再做这部分工作亦可。
