### ISSUE TITLE
Especial Thanks

### ISSUE THREAD

**Issue by lizho** [ketoo/NoahGameFrame#128]
It's the very biggest pity that our project of game has been dropped. In most time, NoahGameFrame works so well that I just need to write few code to develop our service.
Due to the end of this project, I can hardly help to improve NoahGameFrame more.
Many thanks to NoahGameFrame, it helped me a lot.
Good luck.

**Comment by ketoo** [comment]
It's so sad to hear that your project has been terminated. Thanks for your help in developing the game frame, it's my honour that NF can help you to save your time in the business environment.

I hope that you can start your new project soon and keep your eye on NF in the future.

Good luck.

**Comment by MrKOTOKU** [comment]
> It's the very biggest pity that our project of game has been dropped. In most time, NoahGameFrame works so well that I just need to write few code to develop our service.
> Due to the end of this project, I can hardly help to improve NoahGameFrame more.
> Many thanks to NoahGameFrame, it helped me a lot.
> Good luck.

hi, me need programmers, maybe you interesting my project?
pls, contact me: mrkotoku@gmail.com
