### ISSUE TITLE
Game object collision

### ISSUE THREAD

**Issue by MiLoserDie** [ketoo/NoahGameFrame#129]
Hello, NF support game object collision?
I need to check the collision of two *players or objects on the server

**Comment by ketoo** [comment]
Sorry, now NF don't support the feature about the physic collision. You can judge the position of these two players to know whether they have collided.

**Comment by MrKOTOKU** [comment]
> Sorry, now NF don't support the feature about the physic collision. You can judge the position of these two players to know whether they have collided.

1) How many users can sustain simultaneously?
2) Does he support the ability to place worlds on different machines and conveniently contact each other?
3) Is there protection from DDOS?

Where can I find the answers to all the questions?

**Comment by ketoo** [comment]
> > Sorry, now NF don't support the feature about the physic collision. You can judge the position of these two players to know whether they have collided.
> 
> 1. How many users can sustain simultaneously?
> 2. Does he support the ability to place worlds on different machines and conveniently contact each other?
> 3. Is there protection from DDOS?
> 
> Where can I find the answers to all the questions?

1. It's hard to say a specific number as the workload depends on how your business complexity and your code quality. In my experiences, I developed a ARPG game and the workload of this game server is 6K-8K players(one server). 

2. In future, we will support the RPC feature to meet this requirement.

3. General speaking, against the DDOS is the internet provider responsibility.
