### ISSUE TITLE
How it's work in Tutorial4

### ISSUE THREAD

**Issue by MiLoserDie** [ketoo/NoahGameFrame#134]
Hello, im find this tutorial4 and he use this code

```
bool NFCHelloWorld4Module::AfterInit()
{
	
	std::cout << "Hello, world4, AfterInit" << std::endl;

	m_pActorModule = pPluginManager->FindModule<NFIActorModule>();

	int nActorID = m_pActorModule->RequireActor();
	m_pActorModule->AddComponent<NFCHttpComponent>(nActorID);
	m_pActorModule->AddDefaultEndFunc(nActorID, this, &NFCHelloWorld4Module::HttpRequestAsyEnd);

	for (int i = 0; i < 10; ++i)
	{
		m_pActorModule->SendMsgToActor(nActorID, NFGUID(10, 20), i, "Test actor!");
	}

	std::cout << "Hello, world4, AfterInit end" << std::endl;

	return true;
}
```

How he call:
`m_pActorModule->SendMsgToActor(nActorID, NFGUID(10, 20), i, "Test actor!");`
if this func not take 4 args?

https://github.com/ketoo/NoahGameFrame/blob/3b3a7220eaeb6f061ae7d4858d0f14c9acf8f8a2/NFComm/NFActorPlugin/NFCActorModule.cpp#L138

**Comment by ketoo** [comment]
Hi, this interface has been changed as a new one and the tutorial4 has been updated too on the master branch, please see the latest code.
