### ISSUE TITLE
关于插件静态库链接

### ISSUE THREAD

**Issue by upxiaoyi** [ketoo/NoahGameFrame#140]
您好，作者
想请问下，插件动态库链接全部换成静态库链接是出于什么考虑的呢？
如果全部静态库链接，那么所有的server都会链接重复的 插件，比如每个server都会链接好友业务插件。
这样每个进程不是包括了很多自己用不到的插件。

**Comment by ketoo** [comment]
是的，所有的插件都会被链接进去，但是使用的时候只会使用你配置文件配置过后再实例化后的插件。
静态链接的好处是C++ 因为平台的原因，部分系统的版本上一些库会有一些细微的差别，为了屏蔽这些差别，一般linux下会使用纯静态链接（即C库也静态）。

当然，你可以选择使用动态链接，只需要把动态链接的宏打开即可使用动态库。

**Comment by MacroGu** [comment]
能不能将具有参考修改意义的Tutorial里面的库改写成动态的，因为逻辑项目可能需要动态加载， 或者两者都支持，谢谢！

**Comment by ketoo** [comment]
部分静态和部分动态的需求，需要使用者自己修改，这类需求不合适放到框架中去。
