### ISSUE TITLE
Help, more info about server role

### ISSUE THREAD

**Issue by MiLoserDie** [ketoo/NoahGameFrame#141]
Hello, can you pls help?
I launched NF, but I cannot understand the role of the "Proxy" and "Master" servers.
How data is transferred (server to server) and how I can configure IP and Port in Server.xml so that clients can connect, but the connection between the servers was local.

**Comment by MrKOTOKU** [comment]
Also, does NF support packet serialization?

**Comment by MrKOTOKU** [comment]
and have other problem, If __asm is used, the compiler breaks, im try use this 

```
short GET_16BIT_INT(const char *p) {
	short d;
	__asm
	{
		mov esi,p
		mov ax,[esi]
		xchg al,ah
		mov d,ax
	};
    return d;
}
```
Why compiler crashed if use this construction? In other project all work, in NF im try compile and Optimizer crashed

**Comment by MrKOTOKU** [comment]
Oh, i know why compiler crashed, NF it's x64, my script for x32

**Comment by ketoo** [comment]
My advice is don't use assembly code in your project as it's hard to maintain.

The role "Proxy" work as a gateway between servers and clients, and the job of "proxy" is to transfer the message and do a check for the message that comes from clients.

The role "Master" is a top server that stores all world's information, such as how many worlds now running. BTW, the role "master" also transfer the message that when the client requires a "proxy" to connect after log on.

**Comment by MrKOTOKU** [comment]
Unfortunately, I did not find examples of how to use them correctly to configure NF for my game.
Need more tutorials for NF  :(

**Comment by ketoo** [comment]
The architecture chart shows the role of each server, you and step by step use it under tutorials where at [](https://github.com/ketoo/NoahGameFrame/wiki)
