### ISSUE TITLE
How create .proto file and disable protobuf?

### ISSUE THREAD

**Issue by MrKOTOKU** [ketoo/NoahGameFrame#142]
Hello, im try use NF for my game.
Im not understand how use "NFMsg" in callback, he use protobuf, but me need use defualt method, without protobuf. And how create NFMsg for my packets in .proto files? And where he taked NFMsg set_event_code and set__... comands?

After failure im try create my array, not use NFMsg (.proto) files
i'm create "char xMsg[1024]", push array bytes for test and try send on serve use 

Bytes in xMsg "00 00 00 04 00 00 00 02 00 00 00 08"
`
m_pNetModule->SendMsg(3, xMsg, nSockIndex);
`

But, in SendMsg function the array xMsg is nulled, why? 
SendMsg function correct read аirst  arg - OpCode, but the second transmitted incorrectly.

**Comment by MrKOTOKU** [comment]
I figured out what the problem is, I try to pass a "char" when "SendMsg" takes a String, but I still can't figure out how to create my own structures in NFDefine.proto and use them.
Can you help?

**Comment by MrKOTOKU** [comment]
If I'm not mistaken, I need to edit NFDefine.proto to fit my settings, however, I don't want to use protobuf. How to use NFDefine.proto without using protobuf to transfer a packet in m_pNetModule->SendMsg?

**Comment by MrKOTOKU** [comment]
Everything, I figured it out!
These .proto files are needed if you use "protobuf", if you don’t, need protobuf, simply convert char to string indicating the length of the string during the conversion, otherwise it will interpret the value of zeros as the end of the string.

**Comment by ketoo** [comment]
> Hello, im try use NF for my game.
> Im not understand how use "NFMsg" in callback, he use protobuf, but me need use defualt method, without protobuf. And how create NFMsg for my packets in .proto files? And where he taked NFMsg set_event_code and set__... comands?
> 
> After failure im try create my array, not use NFMsg (.proto) files
> i'm create "char xMsg[1024]", push array bytes for test and try send on serve use
> 
> Bytes in xMsg "00 00 00 04 00 00 00 02 00 00 00 08"
> `m_pNetModule->SendMsg(3, xMsg, nSockIndex);`
> 
> But, in SendMsg function the array xMsg is nulled, why?
> SendMsg function correct read аirst arg - OpCode, but the second transmitted incorrectly.

You can pass the parameter with string and PB object for transferring to the client.

BTW, the "send" function signature show as below:

`virtual bool SendMsg(const uint16_t nMsgID, const std::string& xData, const NFSOCK nSockIndex);
`

The best way to send message success is to pass the parameter with std::string.

**Comment by ketoo** [comment]
> I figured out what the problem is, I try to pass a "char" when "SendMsg" takes a String, but I still can't figure out how to create my own structures in NFDefine.proto and use them.
> Can you help?
> Im try use converter char to string, but NF accept structure, it's not correct method, need use NFDefine.proto structures, but i don't know how create NFDefine.proto for my game

You would have a look about how to use protocol-buf.

**Comment by ketoo** [comment]
> If I'm not mistaken, I need to edit NFDefine.proto to fit my settings, however, I don't want to use protobuf. How to use NFDefine.proto without using protobuf to transfer a packet in m_pNetModule->SendMsg?

Yes, you can use SendMsg function without protobuf, just using std::string instead of using protobuf.

**Comment by MrKOTOKU** [comment]
I liked the NF, I was able to master it in 2 days. It is a pity that there is little documentation.
Are you the only one who is currently developing NF?

**Comment by MrKOTOKU** [comment]
By the way, how to add your own xml files to the "Ini" folder? They are not initialized when I try to get it through 
`NF_SHARE_PTR <NFIClass> xLogicClass = m_pClassModule-> GetElement (NFrame :: World :: ThisName ());`
It gives an error that the file was not found inside the "mObjectList"
How to add my .xml to "mObjectList" and after use ?

**Comment by MrKOTOKU** [comment]
> > By the way, how to add your own xml files to the "Ini" folder? They are not initialized when I try to get it through
> > `NF_SHARE_PTR <NFIClass> xLogicClass = m_pClassModule-> GetElement (NFrame :: World :: ThisName ());`
> > It gives an error that the file was not found inside the "mObjectList"
> > How to add my .xml to "mObjectList" and after use ?
> > (I created the .xml file and placed it in the "Ini" folder, I could not mistake the names)
> > I mean, how to Load my .xml to mObjectList
> 
> You would add an excel file in NF's world if you want to add you .xml file, the reason is NF can export the excel file as .xml file automatically.

But im not use World server, im change server architecture and use Login and Proxy server for Auth and MSG, i'm want add my .xml for Login and Proxy server.

I was also interested above about whether NF can parse data serialization (my question is two answers above)

**Comment by ketoo** [comment]
All the servers(included Login and Proxy) must load the .xml file that exported from excel file, so you can add your .xml by adding excel file.
