### ISSUE TITLE
Game session

### ISSUE THREAD

**Issue by MrKOTOKU** [ketoo/NoahGameFrame#143]
Hi, how the session check is done in NF to prevent twice authorization on the one account?

The fact is that the authorization server somehow needs to communicate with other servers in order to somehow transfer account state from one server to another, but I could not figure out how to do this without using Redis.
If the function of sending a packet to another server would support returning the callback, it would be great, but this is not possible in NF.
How can I solve my problem without using Redis to store online session accounts?

Thank you for your patience.

**Comment by MrKOTOKU** [comment]
By the way, how can I write Cyrillic in Redis?
I get the character's name in the "char" array, however, Redis does not support Cyrillic. How can I convert and put the data in Redis as Cyrillic, but to support the Latin alphabet?

**Comment by ketoo** [comment]
> Hi, how the session check is done in NF to prevent twice authorization on the one account?
> 
> The fact is that the authorization server somehow needs to communicate with other servers in order to somehow transfer account state from one server to another, but I could not figure out how to do this without using Redis.
> If the function of sending a packet to another server would support returning the callback, it would be great, but this is not possible in NF.
> How can I solve my problem without using Redis to store online session accounts?
> 
> Thank you for your patience.

Normally we store the token information in Redis or in memory that belongs the server.

It's an easy way to achieve your goal if you store the token information in Redis as all servers can access Redis to judge whether the token is expired.

But if you want to store your token in the memory which belongs to the application, you would transfer the token information by you need and change it by yourself.

**Comment by ketoo** [comment]
> By the way, how can I write Cyrillic in Redis?
> I get the character's name in the "char" array, however, Redis does not support Cyrillic. How can I convert and put the data in Redis as Cyrillic, but to support the Latin alphabet?

The best way is to use UTF8  format and transfer it as a string to store in Redis.
