### ISSUE TITLE
NFCProxyServerToGameModule中AfterInit没连接gameServer的逻辑

### ISSUE THREAD

**Issue by sunshang1736** [ketoo/NoahGameFrame#145]
你好，有两个问题请问下
1.我在NFCProxyServerToGameModule中没找到连接gameServer的逻辑，是在别处还是?
2.在NFCWorldNet_ServerModule中维护了dbServer并接收其消息，但看架构worldServer应该只保存gameServer和proxyServer的peer。

**Comment by ketoo** [comment]
1：有链接

proxy本身并不知道gameserver有多少个（扩容等因素），因此设计上是：proxy本身并不是以开始就去链接gamesevrer，而是先链接world，等待world告诉proxy现在有多少gameserver，然后再去链接所有的gameserver，这样你可以在中途随意扩容各类服务器。

处理的代码在函数NFCProxyServerToWorldModule::OnServerInfoProcess
里面的 case NF_SERVER_TYPES::NF_ST_GAME:

2：这一块在设计上略有调整，因为不是特别重要的部分，因此就没更新在架构图上了。
