### ISSUE TITLE
hiredis in NF

### ISSUE THREAD

**Issue by ghost** [ketoo/NoahGameFrame#147]
Hello, NF framework not use async hiredis?
I'm test Redis use  clock(); for get results, and he left 0,011 time on get respond from Redis server (i'm use server Redis on local machine, where i'm start server)
is HMGET function is blocking?
here example
![image](https://user-images.githubusercontent.com/26442550/52102527-efadc680-25f1-11e9-95b8-a231680be116.png)
![image](https://user-images.githubusercontent.com/26442550/52102539-0522f080-25f2-11e9-957e-cdc2d2d9ead3.png)
![image](https://user-images.githubusercontent.com/26442550/52102533-fdfbe280-25f1-11e9-9a7b-c7475a34e8c1.png)

Time statistic:
Inventory Create Left: 0,015 time
Inventory Get Free Slot Left: 0,010~0,011 time
Why Redis eat 10 ms?

i'm find here example for async Redis
https://github.com/redis/hiredis/blob/master/examples/example-libevent.c

Soo, what problem?

**Comment by ketoo** [comment]
First of all, we would know what is the business environment of using Redis?
Secondly, is that block the main thread is acceptable?

In my view,  it's acceptable for using Redis to store or read account information in the login system, the reason is normally we don't do any other business logic in this thread so we wouldn't give the player a bad user experience.

Of cause, you can use Redis with an async mode if you like, but you will hard to maintain your code as callback hell.

**Comment by MrKOTOKU** [comment]
Do you recommend leaving as is? 

Other quest:
Can I use Redis as a basis for keeping data permanently? If I use AOF mode to save data every second to the hard disk.

**Comment by ketoo** [comment]
It's ok for you to use Redis with AOF mode, how frequently to save the data dependent your business needs.

You would read the doc at https://redis.io/topics/persistence to know the answer.

**Comment by MrKOTOKU** [comment]
> It's ok for you to use Redis with AOF mode, how frequently to save the data dependent your business needs.
> 
> You would read the doc at https://redis.io/topics/persistence to know the answer.

Thank's!

**Comment by MiLoserDie** [comment]
> It's ok for you to use Redis with AOF mode, how frequently to save the data dependent your business needs.
> 
> You would read the doc at https://redis.io/topics/persistence to know the answer.

Nevertheless, should I use Redis to store all data: Auth, MSG and World servers?
This is a large amount of data.

Or use MySQL for World and Redis for Auth and MSG server?
