### ISSUE TITLE
Object 3D distance

### ISSUE THREAD

**Issue by MiLoserDie** [ketoo/NoahGameFrame#148]
Hello, i need to get a distance between two players and make one player follow the other, but keep a small distance
Example, i have 2 player: PlayerA and PlayerB
```

PlayerA.PositionX = 500.0
PlayerA.PositionZ = 0.0
PlayerA.PositionY = 100.0

PlayerA.PositionX = 200.0
PlayerA.PositionZ = 0.0
PlayerA.PositionY = 300.0
```

How can I get the distance between them? I need to get a vector? (Use NF)
Me need 2 example, first: use X,Z,Y coords; second: use X,Y (in 3D, but not used height Z coord)

Here example:
![image](https://user-images.githubusercontent.com/26442550/52627190-e3fdb200-2ec5-11e9-9121-e34a4d779066.png)

And, if i'm not mistake, me need get character position and add object radius to vector, for get object size and create correct collision

**Comment by ketoo** [comment]
First of all, you would know the position by using the function below:

`virtual const NFVector3& GetPropertyVector3(const NFGUID& self, const std::string& strPropertyName);
`
Secondly, you can use the function named "Distance" that belong to the class NFVector3 to know the distance between two positions.
`float Distance(const NFVector3& v) const`

**Comment by MrKOTOKU** [comment]
Can you explain what the following functions are used for and how to use them:
"SquaredMagnitude", "Magnitude", "Direction"?

**Comment by ketoo** [comment]
You would google to know how to use it, it's the general function of the mathematics library.
