### ISSUE TITLE
Adding Flatbuffers to NF

### ISSUE THREAD

**Issue by ghost** [ketoo/NoahGameFrame#157]
Hi, I like the NF framework and I recently found Google flatbuffers.
It would be very useful to add flatbuffers to NF by adding specific API commands for NF to interact with Flatbuffers.

Flatbuffers can store data in Redis, as well as, when storing data in flatbuffers, you do not need to unpack it for reading / use. This is a convenient library for storing data and structures of NPCs, monsters.
https://github.com/google/flatbuffers

What do you think about it?

**Comment by ketoo** [comment]
Google flatbuffers is a great lib.

I have the plan to add flatbuffers to NF but I have not enough time to do this recently, so I hope someone can help NF to do this and I will assist this job.
