### ISSUE TITLE
ScheduleModule guide ?

### ISSUE THREAD

**Issue by MiLoserDie** [ketoo/NoahGameFrame#159]
Hello, give examples of how to use this function. Does it work stably?
This is a very useful feature to perform tasks at a specific time!
https://github.com/ketoo/NoahGameFrame/blob/449d1be0969d95025a3bad9f14ac99a75d97a3d9/NFComm/NFPluginModule/NFIScheduleModule.h

What do you think, is it worth using this task manager to issue effects to the player and remove effects?

Do I understand correctly that this module is capable of calling functions at a certain time (and he support arguments) for a specific player? 
Is the client ID (NFGUID) or task name used for identification? 
Can the same task name be used for all player IDs (NFGUID)

Please documentation : ( 
oh yea, what is ->
https://github.com/ketoo/NoahGameFrame/blob/0a8e62e1ab258f709036b12082bfad4bbe3b6a08/NFComm/NFKernelPlugin/NFScheduleModule.cpp#L219-L226

Does this module have performance problems?

**Comment by ketoo** [comment]
Hi,

Please see Tutorial3 and Tutorial5 to know how to use the schedule module.

The time scope is to check how much time the schedule used when running, now I have committed a new version and set a  lower standard for it as the server print "module schedule performance problem" frequently.

**Comment by MiLoserDie** [comment]
I have a few questions:
1) Should I register only 1 "Schedule heartbeat" for all tasks or do I create my own "AddSchedule" for each task, example for "Buff" and "Effects", me need use 1 hearbeat or 2 schedule??
2) How productive is the "Schedule Module"?
3) How many tasks does he support at most?

**Comment by ketoo** [comment]
Normally, we are better to register one function for one task. In terms of your example, INF provides a buff module named "NFBuffModule", please have a look at it to know how to process this situation.

General speaking, how many tasks can be held by this module depends on the complexity of your businesses.

In future, the schedule module will support to pass arguments, certainly, you are welcome to do this job. The event module is a separate module that likes the Signal and Slot feature in QT, the code here in tutorial3 just show you how to use it.

**Comment by MiLoserDie** [comment]
I would help with NF improvements, but I don't have enough experience for that :(

**Comment by ketoo** [comment]
Don't worry, maybe the first step is hard, but it will more easy after that.
