### ISSUE TITLE
Change libevent on brynet (update)?

### ISSUE THREAD

**Issue by MiLoserDie** [ketoo/NoahGameFrame#160]
Hello, what you think about change libevent on other fast TCP lib?
Example: https://github.com/IronsDu/brynet
I'm find them in Ark 

It seems to me that libevent is a slightly outdated network protocol, why is libevent used in NF?

**Comment by ketoo** [comment]
Libevent is a stable library and used by many products as an enterprise network communication component.

In my professional experience, the first job is to keep the server stability and running fast when you work as a back end developer, so when you decide to use a library you are better to know whether the library is long-tested. Unfortunately, most of the developers do not play good developer in their position.

**Comment by MiLoserDie** [comment]
> Libevent is a stable library and used by many products as an enterprise network communication component.
> 
> In my professional experience, the first job is to keep the server stability and running fast when you work as a back end developer, so when you decide to use a library you are better to know whether the library is long-tested. Unfortunately, most of the developers do not play good developer in their position.

I ran tests between brynet and libevent.
Here are the results:
Brynet: 0.004 - 0.005 msec on PingPong
libevent: 0.03 - 0.04 msec on PingPong
I think you should check it yourself, it's big difference

Check how long does libevent take to get a response from the local server to which you are sending the packet
For example: Proxy -> Master and Master -> Proxy (Ping - Pong)

**Comment by MiLoserDie** [comment]
@ketoo update, did you see my last post?

**Comment by sniper00** [comment]
asio is more better. http://think-async.com/Asio/

**Comment by sniper00** [comment]
> @ketoo update, did you see my last post?

Asio is more better. http://think-async.com/Asio/

**Comment by MiLoserDie** [comment]
> > @ketoo update, did you see my last post?
> 
> Asio is more better. http://think-async.com/Asio/

In any case, you need to do something with this, this is a huge difference in transmission speed.
I want to note that it was a local area network.

**Comment by ketoo** [comment]
Thanks, asio is good, maybe in the future will improve the network by it.
