### ISSUE TITLE
Error on compiling NF

### ISSUE THREAD

**Issue by TenMei** [ketoo/NoahGameFrame#163]
I try to compile NF (branch master), but it got error. Should I add new property call "PVPType" to Player.xlsx and run ./NFFileProcess again (I don't know how to define it). Please help me solve this problem, thanks so much.
<img width="1042" alt="Screen Shot 2019-05-01 at 16 42 12" src="https://user-images.githubusercontent.com/4993410/57009316-cde3d000-6c30-11e9-950a-b8df2c9970b4.png">

**Comment by ketoo** [comment]
Sorry, my bad, now fixed.
