### ISSUE TITLE
NF and Redis 

### ISSUE THREAD

**Issue by MiLoserDie** [ketoo/NoahGameFrame#165]
What are these methods generally used for?
Could you explain what these functions are generally responsible for?
In the NF examples, some functions, such as VerifyAccount, accept only the string strAccount, and not 
 strAccount + "_AccountInfo "

```
	virtual NFList<std::string> GetDriverIdList() = 0;
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriver(const std::string& strID) = 0;
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriverBySuitRandom() = 0;
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriverBySuitConsistent() = 0;
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriverBySuit(const std::string& strHash) = 0;
```

**Comment by ketoo** [comment]
In the NF examples, some functions, such as VerifyAccount, accept only the string strAccount, and not
strAccount + "_AccountInfo "
----------------Just a name to remember it easier, you can change as you like.

virtual NFList<std::string> GetDriverIdList() = 0;
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriver(const std::string& strID) = 0;
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriverBySuitRandom() = 0;
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriverBySuitConsistent() = 0;
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriverBySuit(const std::string& strHash) = 0;

Imagine that you want to create a scalable database backend with "n" database servers for your application or a distributed system with a cluster of servers. To meet the goal we would meet the rules below:

a.  We should be able to distribute the incoming queries uniformly among the set of "n" database servers
b.  We should be able to dynamically add or remove a database server
c.  When we add/remove a database server, we need to move the minimal amount of data between the servers

        //get redis driver by consistent hashing, normally we use this one
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriverBySuitRandom() = 0;

        //some special features that we want the data away store in a special database we use this one
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriverBySuitConsistent() = 0;

        //get redis driver by the hash value that you pass
	virtual NF_SHARE_PTR<NFIRedisClient>  GetDriverBySuit(const std::string& strHash) = 0;


References below:
[https://www.acodersjourney.com/system-design-interview-consistent-hashing/](url)
[https://en.wikipedia.org/wiki/Consistent_hashing](url)

**Comment by cosmosir** [comment]
for (int i = 0; i < mnNodeCount; ++i)
{
	NFVirtualNode<T> vNode(name, i);
	Insert(vNode);
}
每次添加一个新元素，都向mxNodes添加500个值都为name的数据，这个是测试用的么？感觉这样添加没有意义？
