### ISSUE TITLE
NFScheduleModule time and Count change method

### ISSUE THREAD

**Issue by MiLoserDie** [ketoo/NoahGameFrame#166]
Hello, ketoo
I needed to prolong the time for "AddSchedule", 
I noticed that there was no such implementation, and using RemoveSchedule to call "AddSchedule" again is too expensive.
I propose to add a method to extend the time "Schedule"
for example:
`
virtual bool ChangeTimeSchedule (const std :: string & strScheduleName, const float fTime);`

In addition, the same function can be added for Count, I think it will be useful
`
virtual bool ChangeTimeSchedule (const std :: string & strScheduleName, const int nCount);`

**Comment by MiLoserDie** [comment]
> Hello, ketoo
> I needed to prolong the time for "AddSchedule",
> I noticed that there was no such implementation, and using RemoveSchedule to call "AddSchedule" again is too expensive.
> I propose to add a method to extend the time "Schedule"
> for example:
> ` virtual bool ChangeTimeSchedule (const std :: string & strScheduleName, const float fTime);`
> 
> In addition, the same function can be added for Count, I think it will be useful

**Comment by ketoo** [comment]
Great! It's necessary for some people.

Could you please add this feature for NF? If you want plz send a PR to me, thanks.
