### ISSUE TITLE
How to transfer the status of players from different servers?

### ISSUE THREAD

**Issue by MiLoserDie** [ketoo/NoahGameFrame#167]
I want to create several World and Game servers, but how can I transfer the state of the players and interact with the players if they are on different servers?

For example, PlayerA offers PlayerB trade, but the fact is that PlayerA is located on Proxy-1, which communicates with World-1 and Game-1, and PlayerB is located on Proxy-2, which communicates with World-2 and Game-2.

When PlayerA sends an exchange request to PlayerB, PlayerA's request passes through Proxy-1 -> World-1 and is processed there, but PlayerB uses Proxy-2 and World-2 connection, how do we get PlayerB status and interact with it? 

I know that servers can transfer data to each other through NetClientModule, but I don’t understand how to keep all players' data on each server, and using Redis is not a good idea.

**Comment by ketoo** [comment]
If a player makes a trade with another player face to face, it's not a problem in NF as they all in the same scene. But if a player wants to make a trade with someone who not in the same scene or not online, normally it would happen a virtual bourse. The virtual bourse can run in world server and process the requests for all traders. In terms of the trade data, you can hold it in memory or store in Redis as you like.
