### ISSUE TITLE
在vs下开发的问题

### ISSUE THREAD

**Issue by zzjfengqing** [ketoo/NoahGameFrame#170]
在vs2015下开发，如果要新建一个模块的话 是不是要自己手动去创建一个项目?然后自己添加包含目录和包含库目录，并且制定链接库，是这样的吗？  那cmake是不能生成vs2015项目工程?只能在linux下进行使用,是这样的吗？作者是否考虑用cmake兼容windows和linux下的项目工程生成呢(毕竟cmake本身就是为了跨平台构建项目而生的)？

**Comment by ketoo** [comment]
1）在vs下开发，可以copy原来项目或者教程项目修改，这些项目都有设置好包含库以及链接库，如果要自己重新创建项目，则需要自己设置。通常来说，开新项目的机会少的可怜，因此偶尔开的话复制一下就好。

2）cmake的支持，我目前只是在linux下使用它。之前本来是跨平台产生vs解决方案的，但是因为windows一般有vs我觉得没太大必要就去掉了。

编译文档请查看： [https://github.com/ketoo/NoahGameFrame/wiki/How-to-build-NF](url)

**Comment by zzjfengqing** [comment]
的确是可以通过copy来新建vs项目，方便许多，谢谢答疑。: )

**Comment by ketoo** [comment]
copy来创建新vs项目后，cmake那边只需要加入目录，他会自动包含里面的.h.hpp.cpp等文件，在编译linux版本的时候会自动包含编译。
