### ISSUE TITLE
NFScheduleModule模块的效率问题

### ISSUE THREAD

**Issue by cosmosir** [ketoo/NoahGameFrame#173]
游戏开发中，很多逻辑需要依赖定时器去驱动
这个模块自己通过帧循环进行时间判断，而且没有对触发时间进行排序，每次帧循环都要遍历所有注册的定时器，如果存在大量的定时器，是否会有效率问题？
libevent支持定时器事件（我没有用过，不知道有啥弊端），NF为啥没有利用？

**Comment by ketoo** [comment]
这块是需要优化的，一直想优化成时间排序但是还没开始。

不用libevent的的定时器事件的原因是，只把它当网络库用，避免过多依赖。

**Comment by yk0211** [comment]
定时器模块建议用min_heap实现，然后配合unordered_map标记删除，超时删除策略，查询和删除复杂度都可以达到O(1)

**Comment by ketoo** [comment]
已经优化，现临时采用multiset排序定时器。代码优化到原来的50%，效率很多倍吧，没测过（现在每次循环只获取超时的定时器 然后调用定时器回调函数）。本来打算采用timing wheel的，但是set简单一些，先直接上了。

这个module还有不少优化的地方，比如callback函数的管理，如果直接注入到定时器，回更快（每次callback调用的时候都少几次hash查找）。

[https://github.com/ketoo/NoahGameFrame/commit/cfbf0c37667791aa26bc2ef7b9fbdad996b77112](url)
