### ISSUE TITLE
Development guide

### ISSUE THREAD

**Issue by DNKpp** [ketoo/NoahGameFrame#174]
Well,
I was looking around for a framework which should be able to handle my needs for my moba like mp game. When I have found NF I was pretty amazed about the similarieties to my needs and looked a little bit into the details. It seems fine, but unfortunatly I don't know how to get started, or at least to customize it.
The game will be written in C++ and I'll use protobuf for the network protocol. So, like I said, the similaries are insane. :D

On the other side, I don't want to build my game "inside" of the NF framework, but would like to use just the login and infrastructure abilities. I don't really want to use the property system or something like that. The initial plan was, to load my game as an dll/so into the the game server let NF handle the rest of this. But, is it that easy?
It seems I have to write a plugin for that? That shouldn't be an issue...

On the other side there is lots of documentation missing, so I don't know where to start learning the framework. The few wiki pages are a nice addition, but don't tell me how to setup the framework other than tutorial rdy.

Well, hopefully you find some time for clearance :D

greetings

**Comment by ketoo** [comment]
Hi,

It's a great way to use just the login and infrastructure abilities to start your development without property system.

In terms of your situation, writing a plugin or use the existing plugin both are a good choice for your initial plan, but I will suggest you to use an existing one to have a good start which looks like NFLoginLogicPlugin.

For your game server, just write your business code in NFGameLogicPlugin, this dll/so is the plugin that belongs to your initial plan.

To start your job, the only thing you need know is to know how to use the modules that relative the  network protocol listed below:

````


https://github.com/ketoo/NoahGameFrame/wiki/How-to-login-with-a-new-account

**Comment by DNKpp** [comment]
Thanks for your reply.
I already had a look to the class, but didn't had much time to examine the details.
Is there anywhere a short description of the purpose and tasks of all of these plugins/modules? I find it rather difficult to make guesses about them only by their names.
I think that would make your framework a lot more accessable to people who are new to it. And it shouldn't take too much time to write a few sentecies about those modules.

**Comment by ketoo** [comment]
Thanks for your suggestion, I will continue to write documents to let people know it easier.

The website below I think that what you want.

https://github.com/ketoo/NoahGameFrame/wiki/What-are-the-roles-of-these-servers

**Comment by DNKpp** [comment]
Hey, thanks again for your reply.
Well, that's at least a good start, but it seems it only covers the basic plugins. But, indeed it helps ;)
Unfortunatly I don't have a lot of time to step into your framework; hopefully I'll have some minutes spare at the weekend.

Greetings
