### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by jorlogicus** [ketoo/NoahGameFrame#177]
Greetings, I'm here today to offer my services. As a graphic designer in development and an open-source enthusiast, I wish to contribute to this wonderful project by making a logo for it, the process is totally free and we would be working together to create the design that fits best with your project. Certainly, you can quit whenever you want. In case you agree, I would like to ask you a few simple questions about your project to have a better understanding of it and so deliver a better product, also you could share with me any preferences you may have about colors, shapes, etc.

Sorry for disturbing if this is not the proper channel to request this, best regards.

**Comment by ketoo** [comment]
Hi,

Thanks for your great suggestion and enthusiasm.

It's necessary to design a logo to deliver a better product, please leave your questions to my email(342006@qq.com) then we discuss the details.

**Comment by jorlogicus** [comment]
Sure will! However, I wanted to ask if there weren't any problems by keeping our conversation here on GitHub.

**Comment by ketoo** [comment]
No problem for you to leave you questions here and I will response ASAP.

**Comment by jorlogicus** [comment]
Hello, great! here are the questions: 

- What's the name that should be displayed on the logo, If there should be any?

- How would you describe this project, What is it intended to do?

- What would you like this logo to transmit?

These simple questions will help me a lot in guiding me in the right direction. 

Kind regards.

**Comment by ketoo** [comment]
1) NF
2) A fast, scalable, distributed game server engine/framework for C++, include actor library, network library, can be used as a  real time multiplayer game engine ( MMO RPG/MOBA ).
3) No idea.
