### ISSUE TITLE
Linux Compile Issue

### ISSUE THREAD

**Issue by itsnotyoutoday** [ketoo/NoahGameFrame#183]
Using Ubuntu 16.0.4.6 LTS..

Get the error on ./buildServer.sh

In file included from /home/cryptom_game/NoahGameFrame/Dependencies/libevent/include/event2/bufferevent.h:77:0,
                 from /home/cryptom_game/NoahGameFrame/NFComm/NFNetPlugin/NFNet.h:31,
                 from /home/cryptom_game/NoahGameFrame/NFComm/NFNetPlugin/NFNet.cpp:29:
/home/cryptom_game/NoahGameFrame/Dependencies/libevent/include/event2/visibility.h:30:33: fatal error: event2/event-config.h: No such file or directory
compilation terminated.
NFComm/NFNetPlugin/CMakeFiles/NFNetPlugin.dir/build.make:86: recipe for target 'NFComm/NFNetPlugin/CMakeFiles/NFNetPlugin.dir/NFNet.cpp.o' failed
make[2]: *** [NFComm/NFNetPlugin/CMakeFiles/NFNetPlugin.dir/NFNet.cpp.o] Error 1
CMakeFiles/Makefile2:943: recipe for target 'NFComm/NFNetPlugin/CMakeFiles/NFNetPlugin.dir/all' failed
make[1]: *** [NFComm/NFNetPlugin/CMakeFiles/NFNetPlugin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

real    0m6.527s
user    0m5.348s
sys     0m0.996s

**Comment by ketoo** [comment]
Did you executed the script named "install4cmake.sh"?

You would run the script named "install4cmake.sh" at the first once you download the source, it will build the dependent libraries then build NF.

After that, if you changed the code and want to build NF, just only need to call the script named "buildServer.sh".
