### ISSUE TITLE
mac build error

### ISSUE THREAD

**Issue by yingnierxiao** [ketoo/NoahGameFrame#195]
I'm MacOS
_Out/rund.sh: line 21: cd: Debug: No such file or directory
chmod: NFPluginLoader_d: No such file or directory
_Out/rund.sh: line 25: ./NFPluginLoader_d: No such file or directory
_Out/rund.sh: line 29: ./NFPluginLoader_d: No such file or directory
_Out/rund.sh: line 33: ./NFPluginLoader_d: No such file or directory
_Out/rund.sh: line 37: ./NFPluginLoader_d: No such file or directory
_Out/rund.sh: line 41: ./NFPluginLoader_d: No such file or directory
_Out/rund.sh: line 45: ./NFPluginLoader_d: No such file or directory

**Comment by ketoo** [comment]
Hi, sorry for that, I tested on macOS Mojave 1 min ago, it works. May I know more details as it's hard to know what happens with the information you provided. For instance, what error comes out when you building the system?

**Comment by yingnierxiao** [comment]
sudo sh ./Dependencies/build_dep.sh
Password:
Building dependencies...
grep: /etc/issue: No such file or directory
grep: /etc/*-release: No such file or directory
grep: /etc/issue: No such file or directory
grep: /etc/*-release: No such file or directory
grep: /etc/issue: No such file or directory
grep: /etc/*-release: No such file or directory
grep: /etc/issue: No such file or directory
grep: /etc/*-release: No such file or directory
grep: /etc/issue: No such file or directory
grep: /etc/*-release: No such file or directory
grep: /etc/issue: No such file or directory
grep: /etc/*-release: No such file or directory
grep: /etc/issue: No such file or directory
grep: /etc/*-release: No such file or directory
cmake version 3.15.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip/ ;
see ftp://ftp.info-zip.org/pub/infozip/UnZip.html for other sites.

Compiled with gcc 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-selector-opts) for Unix Mac OS X on Aug 24 2019.

UnZip special compilation options:
        COPYRIGHT_CLEAN (PKZIP 0.9x unreducing method not supported)
        SET_DIR_ATTRIB
        SYMLINKS (symbolic links supported, if RTL and file system permit)
        TIMESTAMP
        UNIXBACKUP
        USE_EF_UT_TIME
        USE_UNSHRINK (PKZIP/Zip 1.x unshrinking method supported)
        USE_DEFLATE64 (PKZIP 4.x Deflate64(tm) supported)
        LARGE_FILE_SUPPORT (large files over 2 GiB supported)
        ZIP64_SUPPORT (archives using Zip64 for large files supported)
        VMS_TEXT_CONV
        [decryption, version 2.11 of 05 Jan 2007]

UnZip and ZipInfo environment options:
           UNZIP:  [none]
        UNZIPOPT:  [none]
         ZIPINFO:  [none]
      ZIPINFOOPT:  [none]
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
automake (GNU automake) 1.16.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
GNU Wget 1.19.5 在 darwin17.5.0 上编译。

-cares +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls 
+ntlm +opie -psl +ssl/openssl 

Wgetrc: 
    /usr/local/etc/wgetrc (系统)
语区: 
    /usr/local/Cellar/wget/1.19.5/share/locale 
编译: 
    clang -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/usr/local/etc/wgetrc" 
    -DLOCALEDIR="/usr/local/Cellar/wget/1.19.5/share/locale" -I. 
    -I../lib -I../lib -I/usr/local/opt/openssl/include -DNDEBUG 
链接: 
    clang -DNDEBUG -lidn2 -L/usr/local/opt/openssl/lib -lssl -lcrypto 
    -ldl -lz ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a -liconv 
    -lintl -Wl,-framework -Wl,CoreFoundation -lunistring 

Copyright © 2015 Free Software Foundation, Inc.
授权 GPLv3+: GNU GPL 第三版或更高版本
<http://www.gnu.org/licenses/gpl.html>。
这是自由软件：您可以自由地更改并重新分发它。
在法律所允许的范围内，没有任何担保。

最初由 Hrvoje Nikšić <hniksic@xemacs.org> 编写。
请将错误报告或建议寄给 <bug-wget@gnu.org>。
LibreSSL 2.8.3
fatal: not a git repository (or any of the parent directories): .git
./Dependencies/build_dep.sh: line 84: cd: Dependencies: No such file or directory
what are you want to do???
Start to build libevent...................................................
./Dependencies/build_dep.sh: line 120: cd: libevent: No such file or directory
./Dependencies/build_dep.sh: line 122: ./autogen.sh: No such file or directory
chmod: ./configure: No such file or directory
./Dependencies/build_dep.sh: line 126: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
cp: directory ../lib/Debug does not exist
cp: directory ../lib/Release does not exist
finished libevent..................................................
Start to build protobuf...................................................
./Dependencies/build_dep.sh: line 138: cd: protobuf: No such file or directory
chmod: *.sh: No such file or directory
./Dependencies/build_dep.sh: line 140: ./autogen.sh: No such file or directory
./Dependencies/build_dep.sh: line 141: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
cp: directory ../lib/Debug does not exist
cp: directory ../lib/Release does not exist
cp: ./src/protoc: No such file or directory
finished protobuf..................................................
Building lua...................................................
rm: lua-5.3.5.tar.gz: No such file or directory
--2019-10-29 00:07:51--  http://www.lua.org/ftp/lua-5.3.5.tar.gz
正在解析主机 www.lua.org (www.lua.org)... 88.99.213.221
正在连接 www.lua.org (www.lua.org)|88.99.213.221|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Found
位置：http://117.128.6.10/cache/www.lua.org/ftp/lua-5.3.5.tar.gz?ich_args2=468-29000704014558_fd3e76980a8c8e4a88417924f5878233_10001002_9c89632ed5c4f9d99438518939a83798_9a26f8e7136dd177167402bf8321bc40 [跟随至新的 URL]
--2019-10-29 00:07:51--  http://117.128.6.10/cache/www.lua.org/ftp/lua-5.3.5.tar.gz?ich_args2=468-29000704014558_fd3e76980a8c8e4a88417924f5878233_10001002_9c89632ed5c4f9d99438518939a83798_9a26f8e7136dd177167402bf8321bc40
正在连接 117.128.6.10:80... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：303543 (296K) [application/gzip]
正在保存至: “lua-5.3.5.tar.gz”

lua-5.3.5.tar.gz                                 100%[=======================================================================================================>] 296.43K  1.44MB/s  用时 0.2s    

2019-10-29 00:07:52 (1.44 MB/s) - 已保存 “lua-5.3.5.tar.gz” [303543/303543])

cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make macosx
/Applications/Xcode.app/Contents/Developer/usr/bin/make all SYSCFLAGS="-DLUA_USE_MACOSX" SYSLIBS="-lreadline"
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lapi.o lapi.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lcode.o lcode.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lctype.o lctype.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o ldebug.o ldebug.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o ldo.o ldo.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o ldump.o ldump.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lfunc.o lfunc.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lgc.o lgc.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o llex.o llex.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lmem.o lmem.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lobject.o lobject.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lopcodes.o lopcodes.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lparser.o lparser.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lstate.o lstate.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lstring.o lstring.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o ltable.o ltable.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o ltm.o ltm.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lundump.o lundump.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lvm.o lvm.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lzio.o lzio.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lauxlib.o lauxlib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lbaselib.o lbaselib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lbitlib.o lbitlib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lcorolib.o lcorolib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o ldblib.o ldblib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o liolib.o liolib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lmathlib.o lmathlib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o loslib.o loslib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lstrlib.o lstrlib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o ltablib.o ltablib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lutf8lib.o lutf8lib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o loadlib.o loadlib.c
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o linit.o linit.c
ar rcu liblua.a lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o lutf8lib.o loadlib.o linit.o 
ranlib liblua.a
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lua.o lua.c
gcc -std=gnu99 -o lua   lua.o liblua.a -lm -lreadline 
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o luac.o luac.c
gcc -std=gnu99 -o luac   luac.o liblua.a -lm -lreadline 
src/lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
cp: directory ../lib/Debug does not exist
cp: directory ../lib/Release does not exist
Building lua finish.............................................
./Dependencies/build_dep.sh: line 177: cd: LuaIntf: No such file or directory
Building hiredis.............................................
chmod: build_hiredis.sh: No such file or directory
./Dependencies/build_dep.sh: line 184: ./build_hiredis.sh: No such file or directory
Building hiredis finish.............................................
/

**Comment by JamesJBA** [comment]
fatal: not a git repository (or any of the parent directories): .git

The command has to be entered in the directory of the repository. The error is complaining that your current directory isn't a git repo.

Could you please enter the folder manually with the command cd Dependencies? After that run the command below: sudo sh build_dep.sh? then it should works (I tested).

**Comment by ketoo** [comment]
fatal: not a git repository (or any of the parent directories): .git

The command has to be entered in the directory of the repository. The error is complaining that your current directory isn't a git repo.

Could you please enter the folder manually with the command cd Dependencies? After that run the command below: sudo sh build_dep.sh? then it should works (I tested).
