### ISSUE TITLE
vcpkg 无法使用

### ISSUE THREAD

**Issue by Addision** [ketoo/NoahGameFrame#197]
你好，能不能换成其他包管理工具，vcpkg windwos 环境真的没办法使用啊

**Comment by ketoo** [comment]
你好，没办法使用请问是下载不了依赖库吗还是其他的？

我后面打算把之前的依赖库编译脚本提交上去，提供一个备选项，那个脚本就是直接clone github上的源码本地编译了，但是估计github的速度也是一个问题。
