### ISSUE TITLE
looking for a mature version

### ISSUE THREAD

**Issue by ifivebig** [ketoo/NoahGameFrame#2]
I've browsed the develop code base, the framework seems not mature enough for real project to use. Is there any recommendable version that I could start for my server project?

**Comment by ketoo** [comment]
we will release a new stable version(3.0) next week, them u can use it in u project.
every new version will be compatible with the old version, so it is safe to u to upgrade.

**Comment by eliteYang** [comment]
you can use the newest stable version in 2.0 branch, when 3.0 release, you can upgrade.
Any further questions, please contact us.

**Comment by ifivebig** [comment]
good news. thanks.
