### ISSUE TITLE
NFHttpServer remote_host 异常

### ISSUE THREAD

**Issue by cosmosir** [ketoo/NoahGameFrame#215]
const char* hostname = evhttp_request_get_host(req);
	if (hostname != NULL)
	{
		//evhttp_find_vhost(http, &http, hostname);
		pRequest->remoteHost = hostname;
	}

这个地方的hostname获取的是本机的地址，req里面有remote_host是客户端地址，为啥不用？

**Comment by ketoo** [comment]
我一会看一下。谢谢反馈。

**Comment by ketoo** [comment]
Fixed, thanks.
