### ISSUE TITLE
Document in English

### ISSUE THREAD

**Issue by hoangtrongphuc** [ketoo/NoahGameFrame#22]
How to use this framework ? I can't find English document

**Comment by ketoo** [comment]
Sorry for this, I will write English document soon.
Follow the Tutorial to learn this framework is a good choose.
https://github.com/ketoo/NoahGameFrame/tree/master/Tutorial

**Comment by ketoo** [comment]
http://noahframe.com/NFDoc/html/index.html

**Comment by guisousanunes** [comment]
Some update for a english document or a simples english tutorial? A link for donation for help too, please, I'm searching some game server framework for my Unity3D mmorpg, and loved NoahGameFrame architecture, but I need some english tutorial  :(

**Comment by ketoo** [comment]
Sorry for this, now I am working on [Wiki](https://github.com/ketoo/NoahGameFrame/wiki). The English doc will be out soon.
