### ISSUE TITLE
Unity Client not working

### ISSUE THREAD

**Issue by giorgi-abashidze** [ketoo/NoahGameFrame#234]
hi, i tried to start unity client but login screen not showing because there is exception before that part of code

**FormatException: Input string was not in a correct format.
System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Single.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Single.Parse (System.String s) (at <437ba245d8404784b9fbab9b439ac908>:0)
NFSDK.NFElementModule.LoadInstanceElement (NFSDK.NFIClass xLogicClass) (at Assets/NFSDK/NFConfig/NFElementModule.cs:187)
NFSDK.NFElementModule.Load () (at Assets/NFSDK/NFConfig/NFElementModule.cs:55)
NFSDK.NFElementModule.AfterInit () (at Assets/NFSDK/NFConfig/NFElementModule.cs:33)
NFSDK.NFIPlugin.AfterInit () (at Assets/NFSDK/NFPluginModule/NFIPlugin.cs:41)
NFSDK.NFPluginManager.AfterInit () (at Assets/NFSDK/NFPluginManager/NFPluginManager.cs:54)
NFRoot.Start () (at Assets/NFrame/NFRoot.cs:50)**

i see exception comes from NFElementModule.cs:55 but i don't know too much about this project so i can't fix this, need your help

**Comment by ketoo** [comment]
Hi,

Thanks for your feedback.

Is that this unity sdk now you using? [https://github.com/ketoo/NFUnitySDK](url)

If not, please use this one, this one is the latest unity SDK right now.

Thanks.

**Comment by giorgi-abashidze** [comment]
this sdk got errors after connecting, I recorded video and you can clearly see whats going on,

[here is the video](https://1drv.ms/v/s!Ar3yNofa_E8RjHv-CtpAhmTRTN1g?e=mrija6)

thanks for reply.

**Comment by ketoo** [comment]
I knew what happens, will be fixed today.

**Comment by ketoo** [comment]
Fixed all and I have tested on Windows platform with the latest server and unity SDK, it works well now.

**Comment by giorgi-abashidze** [comment]
Getting same errors, maybe im doing something wrong. I am closing this issue.

**Comment by ketoo** [comment]
Is that run well on unity editor?

**Comment by giorgi-abashidze** [comment]
No, still the same like in the video that i shared to you

**Comment by giorgi-abashidze** [comment]
I need to download redis directly?

**Comment by giorgi-abashidze** [comment]
ok, I downloaded redis and it looks like server is connecting to it, redis window logging "3 clients connected" in every 5 second.

but when i run NFRoot scene in unity nothing happens after connecting and plus there is an NullreferenceException in SendLags function. when i comment sendlags in lagtestModule.cs  -> Execute() function there is no exception but there is still empty scene. after connecting from NFRoot 
it must be show some test scene right?

Would be nice if you will connect my pc with teamviewer

**Comment by ketoo** [comment]
Sound good, please send that information to my email.

**Comment by ketoo** [comment]
Now it works by changing the code below:

using System.Globalization;

 xValue.Set(float.Parse(xAttribute.Value, CultureInfo.InvariantCulture.NumberFormat));
