### ISSUE TITLE
DBProxy存储玩家数据时，怎么解决的并发存储的问题？

### ISSUE THREAD

**Issue by Ricardo666666** [ketoo/NoahGameFrame#239]
DBProxy存储数据的时候用的异步的方式，就有可能产生冲突的情况。
比如：极短的时间内，同时更新玩家的同一数据多次，就可能出现旧的数据覆盖新的数据的情况。
这个问题在NF中是咋解决的呢？（脏数据？每个玩家的存储的时候按顺序存？）

**Comment by ketoo** [comment]
1：为什么会出现极短的时间内出现多次玩家数据同步？
2：对于gamesever来说，存储是异步的，但是对于db来说，存储是同步的，只要send message to db的时候，发送的是同一个db server，就不会存在你说的覆盖问题，因为永远是按照顺序存储。

致于如何确保通一个玩家的消息一直发送到某一个db server，请参考一致性hash到相关内容，send的接口内部都有包含那一部分。

**Comment by Ricardo666666** [comment]
没看到一致性hash 以为gameserver发送的请求是随机到某一个dbserver
