### ISSUE TITLE
C#.

### ISSUE THREAD

**Issue by juliolitwin** [ketoo/NoahGameFrame#243]
Hi @ketoo ,

My impression or was there a little version of NoahGameFrame in C#? If yes, has the C# version been dropped?

It would be great to have a version of NoahGameFrame, it is an excellent framework but in C# it would make it a lot easier. xD

Regards.

**Comment by ketoo** [comment]
Hi,

Yes, [here](https://github.com/ketoo/NFrame) has a little version for C#, but is a broken one and suggests don't use it for the production environment as some modules aren't finished.

Right now, normally [C# version](https://github.com/ketoo/NFUnitySDK) is used with Unity for the client-side. 

Totaly you don't worry C++, using C++ on NF is really easy, don't need to worry about memory, don't need to worry pointer and don't need "new" objects, it's simpler than c #.

**Comment by juliolitwin** [comment]
Thanks,

Do you know any games already in production using NoahGameFrame?

**Comment by ketoo** [comment]
Many, most of is in China market.
