### ISSUE TITLE
How to build it for clion?

### ISSUE THREAD

**Issue by yangcancai** [ketoo/NoahGameFrame#253]
**I  have builded the proj with clion(win10),  clicked debug button,  there something erro message below:**
`
In file included from /cygdrive/h/cam/c++/NoahGameFrame/NFComm/NFMessageDefine/NFDefine.pb.cc:4:
/cygdrive/h/cam/c++/NoahGameFrame/NFComm/NFMessageDefine/NFDefine.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
   10 | #include <google/protobuf/port_def.inc>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /cygdrive/h/cam/c++/NoahGameFrame/NFComm/NFMessageDefine/NFMsgShare.pb.cc:4:
/cygdrive/h/cam/c++/NoahGameFrame/NFComm/NFMessageDefine/NFMsgShare.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
   10 | #include <google/protobuf/port_def.inc>`

**could you help me how to solve this problem**

**Comment by ketoo** [comment]
This error means that you miss some head files of protocol-buf, did you have a look at this page? https://github.com/ketoo/NoahGameFrame/wiki/Tutorial:-CompileNF

Way 1: Please use VPN to download the dependence libraries(vcpkg) If you living in Mainland.
Way2: Run the script named 墙内下载依赖库.bat to download the dependence libraries and use VS2019 as you IDE if you use Windows.

**Comment by yangcancai** [comment]
use VS2019 IDE is ok
