### ISSUE TITLE
CUP 占用率异常

### ISSUE THREAD

**Issue by lcals** [ketoo/NoahGameFrame#279]
Merge pull request #277 from ketoo/blueprint

合并后 ubuntu 上CUP 占用率异常

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.78    1.146562           2    419726           epoll_wait
  0.16    0.001888          13       139           clock_nanosleep
  0.02    0.000178          29         6           writev
  0.01    0.000167           8        20           write
  0.01    0.000096           2        36           lseek
  0.01    0.000064           2        22        18 ioctl
  0.00    0.000038           9         4           readv
  0.00    0.000032          16         2           openat
  0.00    0.000030           2        12           epoll_ctl
  0.00    0.000013           3         4           read
  0.00    0.000008           4         2           close
  0.00    0.000008           2         4           rt_sigaction
  0.00    0.000008           2         4           rt_sigprocmask
  0.00    0.000006           3         2           fstat
------ ----------- ----------- --------- --------- ----------------
100.00    1.149098                419983        18 total

**Comment by ketoo** [comment]
确认，周末会fix。

**Comment by ketoo** [comment]
Fixed.
