### ISSUE TITLE
client can not connect to server

### ISSUE THREAD

**Issue by ifivebig** [ketoo/NoahGameFrame#3]
hi guys, I was playing with the demo and find two problems:
1. _Out\Server\NFDataCfg\mysql\NFrame.sql does not have accountinfo table.
2. No register function button in unity client.

NFLoginServer log content:

[INFO  | 2015-06-27 21:05:03,439] | Indent[0-0] NF_NET_EVENT_CONNECTED connectioned success NFCLoginToMasterModule::OnSocketMSEvent 235
[INFO  | 2015-06-27 21:05:03,444] | Indent[0-106001] LoginServer_1 Register
[INFO  | 2015-06-27 21:05:03,452] | Indent[0-1]  WorldInfo
[INFO  | 2015-06-27 21:06:01,213] | Indent[0-516] NF_NET_EVENT_CONNECTED connectioned success NFCLoginNet_ServerModule::OnSocketClientEvent 312
NFNet || 非法消息:unMsgID=100
BadQuery [query error] Error: Table 'app_test.accountinfo' doesn't exist
NFNet || 非法消息:unMsgID=100
NFNet || 非法消息:unMsgID=100
NFNet || 非法消息:unMsgID=100
NFNet || 非法消息:unMsgID=100

**Comment by ketoo** [comment]
hi guys,sorry for  forgot to upload another SQL file, i l submit it  tomorrow.

1: u need to create 2 tables ike this:
AccountInfo[3 key]
ID[string],Password[string],RoleID[string]

RoleInfo:[3 key]
ID[string], Property[blob], Record[blob]

2:generally, people used to register their account on the website, so u need to create account by yourself like this:ID[test1] and Password[123456],then u can use this account to login.

**Comment by ketoo** [comment]
hi guys,  accountinfo table has be upload in this folder "_Out\Server\NFDataCfg\mysql\", name is "app_test.sql".

"NFrame.sql" will be used in the future, it's easy to use and maintenance.

If have any other questions, welcome to contact us.
