### ISSUE TITLE
VS2019 can't build with lua error

### ISSUE THREAD

**Issue by lustlord** [ketoo/NoahGameFrame#315]
![image](https://user-images.githubusercontent.com/2193678/111895529-94193f80-89e9-11eb-8351-e2137aac4269.png)
hi I tried to build with vs 2019, but lua can't pass through.

**Comment by ketoo** [comment]
Lua 5.4 upgrade this function but Luabind didn't follow it.

I will do an update for this to let it works this week for Windows.

**Comment by lustlord** [comment]
> Lua 5.4 upgrade this function but Luabind didn't follow it.
> 
> I will do an update for this to let it works this week for Windows.

Thanks a lot :)

**Comment by ketoo** [comment]
Now it works by using Lua 5.3, just need to clone the repo and run Dependencies/build_dep.bat.

**Comment by xinst** [comment]
@lustlord  if it works, pls let me know, it works for me.
