### ISSUE TITLE
win7  vs2015 compile failure

### ISSUE THREAD

**Issue by scanor** [ketoo/NoahGameFrame#34]
cannot start program“NoahGameFrameRoot\\_Out\Release\NFPluginLoader.exe”.

**Comment by ketoo** [comment]
Yes, u can not run "NFPluginLoader.exe” directly.
You need to run it with some parameters when you don's use script, please use script "_Out\runr.bat" as a reference. BTW, please use the script "_Out\runr.sh" as a reference if you want to run the execute file in Linux.

**Comment by ketoo** [comment]
Windows runner:
cd Release

echo Starting NFMasterServer...
start "NFMasterServer" "NFPluginLoader.exe" "Server=MasterServer" "ID=3"

choice /t 2 /d y /n >nul
echo Starting NFWorldServer...
start "NFWorldServer" "NFPluginLoader.exe" "Server=WorldServer" "ID=7"

choice /t 5 /d y /n >nul

echo Starting NFLoginServer...
start "NFLoginServer" "NFPluginLoader.exe" "Server=LoginServer" "ID=4"

choice /t 2 /d y /n >nul

echo Starting NFGameServer...
start "NFGameServer" "NFPluginLoader.exe" "Server=GameServer" "ID=6"

choice /t 4 /d y /n >nul

echo Starting NFProxyServer...
start "NFProxyServer" "NFPluginLoader.exe" "Server=ProxyServer" "ID=5"

Linux runner:
export LC_ALL="C"

cd Release

chmod -R 777  NFPluginLoader

./NFPluginLoader -d Server=MasterServer ID=3

./NFPluginLoader -d Server=WorldServer ID=7

./NFPluginLoader -d Server=LoginServer ID=4

./NFPluginLoader -d Server=GameServer ID=6

./NFPluginLoader -d Server=ProxyServer ID=5

ps -A|grep NF

**Comment by scanor** [comment]
（If you don't know chinese, please tell me.）
感谢你的及时回答！希望你能看懂中文，因为我英语水平目前仅限于听力和阅读，尚不能写和翻译，请原谅。 当我在命令行执行install4vs.bat的时候，提示我'NfFileProcess.exe' 不是内部或外部命令，也不是可运行的程序。我忽略这个提示，用vs2015打开这个解决方案的时候，发现有一些项目是没有打开的，NFComm文件夹下的都不行，然后我编译整个解决方案的时候也编译不了，提示找不到NFomm下的某些头文件的，请问这个要怎么解决，貌似按照你的提示一步步往下走走不通。不知道你是否有自己重头clone代码编译过，期待能得到你的回复。

**Comment by scanor** [comment]
已解决并且成功运行，再次感谢你的及时回复，继续研究框架中。

**Comment by ketoo** [comment]
感谢提出问题，也可以提出下解决方法，如果有问题我好改一下教程。

**Comment by scanor** [comment]
提示找不到NFComm文件夹下的头文件时，我的解决方案是：点击Configration Manager 然后把所有的project后面的build都勾上，就可以编译了运行了，我这里截个图
![image](https://cloud.githubusercontent.com/assets/12003972/23295798/2d9355ea-faad-11e6-8468-3e42d2e410e2.png)
![image](https://cloud.githubusercontent.com/assets/12003972/23295812/3d722888-faad-11e6-80d9-0a063aa36de1.png)

**Comment by ketoo** [comment]
好的，我fixed一下，估计不小心什么时候点掉了，感谢反馈。

**Comment by ketoo** [comment]
fixed
