### ISSUE TITLE
似乎有个错误

### ISSUE THREAD

**Issue by cx421774557** [ketoo/NoahGameFrame#37]
NoahGameFrame/NFClient/Cocos/Classes/NF/Logic/NFCLogicBase.h   第46行
应该是
mModuleEventPrtMap[pBase] = functorPtr.get();

**Comment by Johance2** [comment]
没错的， 原来就是你说的那样写的。 但是那是错误的，我要存的是。这个绑定的函数是属于哪个类的、
再移除的时候，先通过eventid找到 函数列表， 再通过函数指针找到是同一个类的，然后移除掉。

**Comment by cx421774557** [comment]
喔，还没有细看，刚开始研究。但是这样写后无法编译通过，需要强制转换？

**Comment by Johance2** [comment]
我这边可以编译的。

**Comment by Johance2** [comment]
报错我看一下吧

**Comment by cx421774557** [comment]
稍后，我为了编译过去，修改了一下那个map的模板参数，我先还原

**Comment by cx421774557** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2440	“=”: 无法从“NFCGameScene *”转换为“std::function<int (int,const NFDataList &)> *” (编译源文件 ..\Classes\NF\Scene\NFCGameScene.cpp)	NFDemo	d:\tmp\github\noahgameframe\nfclient\cocos\classes\nf\logic\nfclogicbase.h	46	


但是我将map模板参数改为std::map< MODULE_EVENT_FUNCTOR*, void*> mModuleEventPrtMap; 就没问题了，由于不知道具体架构，所以也不敢乱修改，才来求助的

**Comment by ketoo** [comment]
NoahGameFrame/NFClient/Cocos/Classes/NF/Logic/NFCLogicBase.h 第46行
应该是
mModuleEventPrtMap[pBase] = functorPtr.get();
==================
直接存functorPtr对象不是更好吗。。。。

**Comment by Johance2** [comment]
我这边功能是 需要 移除掉，指定的类的绑定函数，但是 std::fun不知道如何获取那个值。所以多做了一层 fun对应的 classs ptr
之前我弄错目录了。==、 没提交上去。 
std::map<void*, void*> mModuleEventPrtMap; 都改成void*了
