### ISSUE TITLE
NoahGameFrame/README.md

### ISSUE THREAD

**Issue by iiRecord** [ketoo/NoahGameFrame#39]
似乎文档需要更新一下了。

* `Run the binary file by **_Out/Debug/rund.bat` 编译完成后，rund.bat 在 _Out 目录下面了。

* `Run **GenerateConfigXML.bat** to generate configuration files`  在 install4vs.bat 中就已经执行了。所以是不是 clone 下来工程后，就先 build `NFFileProcess` project 这个呢。因为我 clone 下来直接用 vs2015 编译了，发现编译不过去，才看的 README.md ，此时 `NFFileProcess` 已经被 build 完了。

**Comment by ketoo** [comment]
1: 已经修改.
2: 我确认一下然后修改。实现是应该按照说明那样去做的。
