### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ketoo/NoahGameFrame#4]
I would like to point out that identifiers like "[`_NFC_FIGHTSTATE_H_`](https://github.com/ketoo/NoahGameFrame/blob/51161aa2b3bf19494ab08b8fc20fc26a9b74044d/NFServer/NFAIPlugin/Include/NFCFightState.h#L9)" and "[`_NFC_OBJECT_H_`](https://github.com/ketoo/NoahGameFrame/blob/c472a5008f1c5934f05fa32774889ff5f8f4588c/NFComm/NFCore/NFCObject.h#L9)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by ketoo** [comment]
That's a good idea, we will fixed in next version.

**Comment by eliteYang** [comment]
Thanks for your suggestion, we will modify it.

**Comment by ketoo** [comment]
SHA-1: eeeb763ac5743f460032c06e04d436f52c33e303

* reserved identifier violation #4

done

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/ketoo/NoahGameFrame/blob/eeeb763ac5743f460032c06e04d436f52c33e303/NFComm/NFCore/NFCConsistentHash.hpp#L10 "More clean-up for identifers?") left over?

**Comment by ketoo** [comment]
SHA-1: 9bd530a5f2f0ace25ffdae2bc38872816cdf22b3

* reserved identifier violation #4

**Comment by elfring** [comment]
Thanks for [another improvement of affected include guards](https://github.com/ketoo/NoahGameFrame/commit/9bd530a5f2f0ace25ffdae2bc38872816cdf22b3 "Deletion of a few underscores").

**Comment by ketoo** [comment]
done.
 Hi, can u tell me how to find this problem, any tool?

**Comment by elfring** [comment]
How do you think about to reuse a search interface like it is provided by GitHub for any more use cases?

Would you like to try [the software library "Boost Wave"](http://www.boost.org/doc/libs/1_60_0/libs/wave/doc/preface.html "Wave C++ preprocessor library") out (besides other ways for improved [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis"))?

**Comment by ketoo** [comment]
SHA-1: 07542425b87b7cc9d6741cec265886caf9ad3ee3

* reserved identifier violation #4

**Comment by ketoo** [comment]
some time use cpp check and a style.
