### ISSUE TITLE
Win10 VS2017 build client cocos2d-x error

### ISSUE THREAD

**Issue by kienvn** [ketoo/NoahGameFrame#40]
Error	C2440	'=': cannot convert from 'NFCUISelectServer *' to 'std::function<int (int,const NFDataList &)> *' (compiling source file ..\Classes\NF\UI\NFCUISelectServer.cpp)	NFDemo	d:\workspace\billiardserver\nfclient\cocos\classes\nf\logic\nfclogicbase.h	46

**Comment by Johance2** [comment]
develop里面已经修正了的。请参考develop下面的，LogicBase
