### ISSUE TITLE
m_recvBuf收完没清空m_recvBuf大小超过MAX_PACKET_POOL_SIZE会有bug

### ISSUE THREAD

**Issue by bluesky7290** [ketoo/NoahGameFrame#41]
NoahGameFrame/NFClient/UnitySDK/Assets/NFSDK/NFNet/NFCNet.cs 211行m_recvBuf收完要清空
Array.Clear(m_recvBuf, 0, m_recvBuf.Length);

**Comment by Johance2** [comment]
这个没有问题的， len = m_socket.Receive(m_recvBuf, 0, kBufferSize, SocketFlags.None);
每次都是在 m_recvBuf的 0 位置才是写入收到的数据的。

**Comment by bluesky7290** [comment]
测试确实不是这里的问题，接收的时候246行会break掉，ConstDefine.MAX_PACKET_LEN设置1024小一点的时候很快出现，好像接收缓冲区（m_recvPool）只增不减，我在dispatchMsgs()方法while结束加上m_recvPool.Reset()问题好像解决了

**Comment by Johance2** [comment]
MAX_PACKET_LEN 这个是包的最大长度，如果你发的包超过这个，肯定会出问题的。
这个是事先计好的。 m_recvPool.Reset() 你加了这个会导致断包的。

**Comment by Johance2** [comment]
还有，我的m_recvPool是环形缓冲区。  一直绕圈圈的。 到尾部了，会重新再走一圈的。

**Comment by Johance2** [comment]
除非你，的单个包大小，超过我设定的最大包的长度，这就会出现问题。
要嘛设置大点，要吗通讯包，自己不要设计太大。

**Comment by bluesky7290** [comment]
抱歉，刚才服务端客户端一起测试，是我的问题，你的是对的，谢谢
