### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ketoo/NoahGameFrame#5]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [NFCMysqlConnectMgrModule::Shut](https://github.com/ketoo/NoahGameFrame/blob/25b8bf2614bedb875837488dcca460c226b43993/NFComm/NFCluster/NFCMysqlConnectMgrModule.cpp#L32 "NFCMysqlConnectMgrModule::Shut function")
* [NFCPacket](https://github.com/ketoo/NoahGameFrame/blob/25b8bf2614bedb875837488dcca460c226b43993/NFComm/NFNet/NFCPacket.h#L33 "Destructor for NFCPacket")
* [NFCPlatformDataModule::Shut](https://github.com/ketoo/NoahGameFrame/blob/25b8bf2614bedb875837488dcca460c226b43993/NFComm/NFDataNoSqlPlugin/NFCPlatformDataModule.cpp#L30 "NFCPlatformDataModule::Shut function")
* [NFSingleton::ReleaseInstance](https://github.com/ketoo/NoahGameFrame/blob/25b8bf2614bedb875837488dcca460c226b43993/NFComm/NFCore/NFSingleton.h#L65 "NFSingleton::ReleaseInstance function")
* [NFCUUIDModule::BeforeShut](https://github.com/ketoo/NoahGameFrame/blob/25b8bf2614bedb875837488dcca460c226b43993/NFComm/NFKernelPlugin/NFKernelModule/NFCUUIDModule.cpp#L107 "NFCUUIDModule::BeforeShut function")

**Comment by eliteYang** [comment]
Just a bad habit, those checks will be removed, thanks.

**Comment by eliteYang** [comment]
@elfring Thanks again, has been removed, https://github.com/ketoo/NoahGameFrame/commit/ddd5fe1e9e61ab5ca6c305c5fce8dc6588b201f3

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/ketoo/NoahGameFrame/blob/25b8bf2614bedb875837488dcca460c226b43993/NFComm/NFDataNoSqlPlugin/NFCDataNoSqlModule.cpp#L30 "More update candidates") left over?

**Comment by eliteYang** [comment]
Missing some part of files, will continue to remove them. :)

**Comment by eliteYang** [comment]
@elfring Can you tell me what tool you used to check this syntax warning? thanks.

**Comment by elfring** [comment]
A search interface like it is provided by GitHub can also work for static source code analysis to some degree, can't it?

**Comment by eliteYang** [comment]
OK, got a new skill, :+1:

**Comment by elfring** [comment]
Thanks for your small source code improvements.

**Comment by eliteYang** [comment]
Thank you for suggestions of all this details.
