### ISSUE TITLE
Copy executable and dependencies built via cmake to remote machine will fail to start

### ISSUE THREAD

**Issue by zhxilin** [ketoo/NoahGameFrame#66]
Building solution via cmake scripts in my local system (I've tested in CentOS 7),  it works normally.
But after copy all executable , dlls and any dependencies to remote linux matchine, it fails to run the NFPluginLoader.

It seems that cmake will link the dependencies as absolute path for my local machine. The remote machine could not find theses path, so it fails to run.

Anyone has this issue?

**Comment by ketoo** [comment]
https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s

Please read the article that about the library path at Linux OS.

All the scripts on https://github.com/ketoo/NoahGameFrame/tree/develop/_Out/Tester has added: export LD_LIBRARY_PATH(linux)  or export DYLD_LIBRARY_PATH(osx).

**Comment by zhxilin** [comment]
Thanks! It's fixed after add 
`export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH`
into the `rund.sh` script for Linux.
