### ISSUE TITLE
如何控制連接gameserver的client數量

### ISSUE THREAD

**Issue by schwantz** [ketoo/NoahGameFrame#85]
目前所設定的數量是多少？
上限到了後proxyserver是不是會讓新連入的client連接新的gameserver?
可以在哪邊設定上限？

**Comment by ketoo** [comment]
virtual int Initialization(const unsigned int nMaxClient, const unsigned short nPort, const int nCpuCount = 4);

启动网络的时候有设置上限，设置上限后，新进入的client会不被处理，这个地方NF处理的略微粗暴。

client永远不会连接到gameserver，他的任何数据必须经过proxy路由到gameserver，因此他只能连接到proxy。
