### ISSUE TITLE
訊息route?

### ISSUE THREAD

**Issue by schwantz** [ketoo/NoahGameFrame#86]
以下是擷取NFCChatModule.cpp

	case NFMsg::ReqAckPlayerChat_EGameChatType::ReqAckPlayerChat_EGameChatType_EGCT_WORLD:
	{
		m_pNetModule->SendMsgPBToAllClient(NFMsg::EGMI_ACK_CHAT, xMsg);
	}

是送給所有在線的玩家嗎？
訊息是這樣走的嗎？     gameserver->masterserver->proxyserver(s)  

	case NFMsg::ReqAckPlayerChat_EGameChatType::ReqAckPlayerChat_EGameChatType_EGCT_GUILD:
	{
		NFGUID xTargetID = NFINetModule::PBToNF(xMsg.target_id());
		NFGUID xGuildID = m_pKernelModule->GetPropertyObject(nPlayerID, NFrame::Player::GuildID());
		if (!xGuildID.IsNull() && xGuildID == xTargetID)
		{
			//send to world server
			m_pGameServerToWorldModule->TransmitToWorld(xGuildID.nData64, nMsgID, xMsg);
		}
	}
送給本worldserver所有的client？
路徑？

	case NFMsg::ReqAckPlayerChat_EGameChatType::ReqAckPlayerChat_EGameChatType_EGCT_PRIVATE:
	case NFMsg::ReqAckPlayerChat_EGameChatType::ReqAckPlayerChat_EGameChatType_EGCT_TEAM:
	{
		if (xMsg.has_target_id())
		{
			NFGUID xTargetID = NFINetModule::PBToNF(xMsg.target_id());
			if (!xTargetID.IsNull())
			{
				if (m_pKernelModule->GetObject(xTargetID))
				{

				}
				else
				{
					//send to world server
					m_pGameServerToWorldModule->TransmitToWorld(xTargetID.nData64, nMsgID, xMsg);
				}
			}
		}
	}
傳送給單一client或team
路徑？

以上還煩請解說，謝謝！

**Comment by ketoo** [comment]
1）如果NFCChatModule.cpp代码运行在gameserver，消息走向为gameserver->proxyserver(s)
业务消息，是不会从gameserver走向master的。

2）Chat例子只是一个展示例子，逻辑不一定准确，它不代表NF的消息流程，NF的消息流程请参考架构文档 https://github.com/ketoo/NoahGameFrame/wiki/Documentation
