### ISSUE TITLE
vs2017编译错误

### ISSUE THREAD

**Issue by JiangWang01** [ketoo/NoahGameFrame#92]
编译NoahFrameX.sln 出现：Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCChaseState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	16

**Comment by JiangWang01** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2228	left of '.data' must have class/struct/union	NFMysqlPlugin	d:\study files\network\noahgameframe-5.2.4\nfcomm\nfmysqlplugin\nfcmysqldriver.cpp	395	
Error	C2065	'i': undeclared identifier	NFMysqlPlugin	d:\study files\network\noahgameframe-5.2.4\nfcomm\nfmysqlplugin\nfcmysqldriver.cpp	309	
Error	C2228	left of '.data' must have class/struct/union	NFMysqlPlugin	d:\study files\network\noahgameframe-5.2.4\nfcomm\nfmysqlplugin\nfcmysqldriver.cpp	309	
Error	C2228	left of '.length' must have class/struct/union	NFMysqlPlugin	d:\study files\network\noahgameframe-5.2.4\nfcomm\nfmysqlplugin\nfcmysqldriver.cpp	309	
Error	C2065	'i': undeclared identifier	NFMysqlPlugin	d:\study files\network\noahgameframe-5.2.4\nfcomm\nfmysqlplugin\nfcmysqldriver.cpp	395	
Error	C2228	left of '.length' must have class/struct/union	NFMysqlPlugin	d:\study files\network\noahgameframe-5.2.4\nfcomm\nfmysqlplugin\nfcmysqldriver.cpp	395	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCFightState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	16	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCDeadState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	16	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCFightState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	22	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCDeadState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	22	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCAIModule.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	16	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCAIModule.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	22	
Error	C1004	unexpected end-of-file found	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfcdeadstate.cpp	54	
Error	C1004	unexpected end-of-file found	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfcfightstate.cpp	122	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCChaseState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	16	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCChaseState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	22	
Error	C1004	unexpected end-of-file found	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfcaimodule.cpp	211	
Error	C1004	unexpected end-of-file found	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfcchasestate.cpp	87	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCIdleState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	16	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCIdleState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	22	
Error	C1004	unexpected end-of-file found	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfcidlestate.cpp	106	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFAIPlugin.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	16	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFAIPlugin.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	22	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCPatrolState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	16	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCPatrolState.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	22	
Error	C1004	unexpected end-of-file found	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfaiplugin.cpp	51	
Error	C1004	unexpected end-of-file found	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfcpatrolstate.cpp	141	
Error	C2509	'SetHateValue': member function not declared in 'NFCHateModule'	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfchatemodule.cpp	45	
Error	C2511	'const NFGUID &NFCHateModule::QueryMaxHateObject(const NFGUID &)': overloaded member function not found in 'NFCHateModule'	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfchatemodule.cpp	83	
Error	C2509	'QueryHateValue': member function not declared in 'NFCHateModule'	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfchatemodule.cpp	88	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCStateMachine.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	16	
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file NFCStateMachine.cpp)	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfistate.h	22	
Error	C1004	unexpected end-of-file found	NFAIPlugin	d:\study files\network\noahgameframe-5.2.4\nfmidware\nfaiplugin\nfcstatemachine.cpp	83

**Comment by JiangWang01** [comment]
NFMysqlPlugin怎么移除了

**Comment by ketoo** [comment]
数据都存储在nosql里面，如果需要mysql，可以用插件定时backup。
