### ISSUE TITLE
A callback register bug.

### ISSUE THREAD

**Issue by lizho** [ketoo/NoahGameFrame#95]
https://github.com/ketoo/NoahGameFrame/blob/51887d2ed0bfb1f4bdcf031c517aff8f7e7e5865/NFClient/Unity3D/Assets/_NF/_Net/NFBinraryMessageEvent.cs#L58

After a ` +=` operation, a delegate can be a new object. In this case, we can see that:

```
MsgDelegation myDelegationHandler = (MsgDelegation)mhtMsgDelegation[eMsg];
var b1 = object.ReferenceEquals(myDelegationHandler, mhtMsgDelegation[eMsg]); // b1 = true
myDelegationHandler += new MsgDelegation(msgDelegate);
var b2 = object.ReferenceEquals(myDelegationHandler, mhtMsgDelegation[eMsg]); // b2 = false
```

To fix it, just append one line like this:

```
MsgDelegation myDelegationHandler = (MsgDelegation)mhtMsgDelegation[eMsg];
myDelegationHandler += new MsgDelegation(msgDelegate);
mhtMsgDelegation[eMsg] = myDelegationHandler; // fix bug
```

Same issue at https://github.com/ketoo/NoahGameFrame/blob/51887d2ed0bfb1f4bdcf031c517aff8f7e7e5865/NFClient/Unity3D/Assets/_NF/_Net/NFBinraryMessageEvent.cs#L74

**Comment by lizho** [comment]
Maybe `Dictionary<object, MsgDelegation>` is a better way.

**Comment by ketoo** [comment]
Great! Thanks for your feedback.

It will be improved in the next version.

**Comment by ketoo** [comment]
Now the NF Demo named Unity3D has been replaced by the Demo named UnitySDK.
