### ISSUE TITLE
Question about server side programming

### ISSUE THREAD

**Issue by MostHated** [ketoo/NoahGameFrame#97]
Hey there,
    I was originally looking around for a network layer / messaging system for my game and then I came across KBEngine and thought it looked pretty neat but found out it really was not something I would be able to use as it would require me to convert all of my current C# serverside code for my game as well as all my server-side assets to python to be able to use them, so I started looking around more and that brought me here to NGF. 

  That being said, if I already have a lot of my server-side logic already written in C# would I have to rewrite it all in order to use NGF with my game?

Thanks!

**Comment by JellyHuang** [comment]
Hi MostHated:
    How are you? As I know at present NF Engine do not support C#  plugin directly. However, you can use CLI to implement C++ and C# call each other by your self. here's some example.
    https://www.codeproject.com/Questions/476583/callplusc-plusdllplusorplusclasspluswithinplusc
    https://www.codeproject.com/Tips/695387/Calling-Csharp-NET-methods-from-unmanaged-C-Cplusp
    
    FYI, you can check MONO, I don't know too much about this. As I know, MONO could help your C# project Cross to other platform.
		http://www.mono-project.com/
	good luck !!

**Comment by MostHated** [comment]
Thanks for the links, I will be sure to check them out. I use Unity3d for my game, it is based on Mono already, so not sure if that would end up helping or not. Are there any systems similar to this that might work better for my situation out of the box that you might know of?

 So far the ones I have seen, do not support C# on the server side at all. I am thinking I might just have to continue on the way I am currently as I do not want to have to rewrite my entire backend in another language if I don't have to.
